Collections:
  - Name: OFD
    Metadata:
      Training Data:
        - CIFAR-10
    Paper:
      URL: https://arxiv.org/pdf/2104.09044.pdf
      Title: Distilling Knowledge via Knowledge Review
    README: configs/distill/mmcls/reviewkd/README.md
    Converted From:
      Code: https://github.com/dvlab-research/ReviewKD
Models:
  - Name: reviewkd_backbone_logits_resnet50_resnet18_8xb16_cifar10
    In Collection: OFD
    Metadata:
      Location: backbone & logits
      Student:
        Config: mmrazor::vanilla/mmcls/wide-resnet/wrn16-w2_b16x8_cifar10.py
        Weights: https://download.openmmlab.com/mmrazor/v1/wide_resnet/wrn16_2_b16x8_cifar10_20220831_204709-446b466e.pth
        Metrics:
          Top 1 Accuracy: 93.2600
          Top 5 Accuracy: 99.8000
      Teacher:
        Config: mmrazor::vanilla/mmcls/wide-resnet/wrn28-w4_b16x8_cifar10.py
        Weights: https://download.openmmlab.com/mmrazor/v1/wide_resnet/wrn28_4_b16x8_cifar10_20220831_173536-d6f8725c.pth
        Metrics:
          Top 1 Accuracy: 95.4400
          Top 5 Accuracy: 99.8200
    Results:
      - Task: Image Classification
        Dataset: CIFAR-10
        Metrics:
          Top 1 Accuracy: 95.4400
    Config: configs/distill/mmcls/ofd/ofd_backbone_resnet50_resnet18_8xb16_cifar10.py
    Weights: https://download.openmmlab.com/mmrazor/v1/factor_transfer/factor-transfer_backbone_resnet50_resnet18_8xb16_cifar10_train_20220831_201322-943df33f.pth
